const express = require('express');
const router = express.Router();

const authRoutes = require('./auth');
const empresasRoutes = require('./empresas');
const empleadosRoutes = require('./empleados');
const conveniosRoutes = require('./convenios');
const conceptosRoutes = require('./conceptos');
const liquidacionesRoutes = require('./liquidaciones');
const documentosRoutes = require('./documentos');
const reportesRoutes = require('./reportes');
const ausentismosRoutes = require('./ausentismos');
const familiaresRoutes = require('./familiares');
const sucursalesRoutes = require('./sucursales');
const parametrosRoutes = require('./parametros');
const ivaRoutes = require('./iva');
const contabilidadRoutes = require('./contabilidad');
const usuariosRoutes = require('./usuarios');
const estudioRoutes = require('./estudio');
const adminRoutes = require('./admin');
const gananciasRoutes = require('./ganancias');
const iibbRoutes = require('./iibb');
const vencimientosRoutes = require('./vencimientos');
const certificadosRoutes = require('./certificados');
const bancosRoutes = require('./bancos');
const honorariosRoutes = require('./honorarios');
const monotributoRoutes = require('./monotributo');
const presupuestoRoutes = require('./presupuesto');
const cambiosRoutes = require('./cambios');
const externoRoutes = require('./externo');
const facturacionRoutes = require('./facturacion');
const dashboardRoutes = require('./dashboard');
const searchRoutes = require('./search');
const webhooksRoutes = require('./webhooks');
const contribucionesRoutes = require('./contribuciones');
const portalRoutes = require('./portal');
const portalClienteRoutes = require('./portalCliente');
const asistenteRoutes = require('./asistente');
const whatsappRoutes = require('./whatsapp');
const afipRoutes = require('./afip');

router.use('/auth', authRoutes);
router.use('/empresas', empresasRoutes);
router.use('/empleados', empleadosRoutes);
router.use('/convenios', conveniosRoutes);
router.use('/conceptos', conceptosRoutes);
router.use('/liquidaciones', liquidacionesRoutes);
router.use('/documentos', documentosRoutes);
router.use('/reportes', reportesRoutes);
router.use('/ausentismos', ausentismosRoutes);
router.use('/familiares', familiaresRoutes);
router.use('/sucursales', sucursalesRoutes);
router.use('/parametros', parametrosRoutes);
router.use('/iva', ivaRoutes);
router.use('/contabilidad', contabilidadRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/estudio', estudioRoutes);
router.use('/admin', adminRoutes);
router.use('/ganancias', gananciasRoutes);
router.use('/iibb', iibbRoutes);
router.use('/vencimientos', vencimientosRoutes);
router.use('/certificados', certificadosRoutes);
router.use('/bancos', bancosRoutes);
router.use('/honorarios', honorariosRoutes);
router.use('/monotributo', monotributoRoutes);
router.use('/presupuesto', presupuestoRoutes);
router.use('/cambios', cambiosRoutes);
router.use('/tipos-cambio', cambiosRoutes);
router.use('/externo', externoRoutes);
router.use('/facturacion', facturacionRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/search', searchRoutes);
router.use('/webhooks', webhooksRoutes);
router.use('/contribuciones', contribucionesRoutes);
router.use('/portal', portalRoutes);
router.use('/portal-cliente', portalClienteRoutes);
router.use('/asistente', asistenteRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/afip', afipRoutes);

module.exports = router;
